version: "3.9"

services:
  db:
    image: postgres:16
    container_name: agenda_db
    environment:
      POSTGRES_DB: agenda
      POSTGRES_USER: agenda_user
      POSTGRES_PASSWORD: agenda_pass
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agenda_user -d agenda"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    container_name: agenda_app
    environment:
      DATABASE_URL: postgresql+psycopg://agenda_user:agenda_pass@db:5432/agenda
    ports:
      - "5000:5000"
    depends_on:
      db: 
        condition: service_healthy
    
    command: sh -c "python init_db.py && python -m flask run --host=0.0.0.0 --port=5000"
    


volumes:
  postgres_data: