version: "3.9"

services:
  db:
    image: postgres:16
    container_name: agenda_db
    environment:
      POSTGRES_DB: agenda
      POSTGRES_USER: agensa_user
      POSTGRES_PASSWORD: agensa_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: