apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-postgres-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "bade908e-0d4a-484b-b636-5c32f77bad7b"
    keyvaultName: "agenda-dev-kv"
    tenantId: "67917f2b-d00c-4dfc-81e0-dfdcf9d31486"
    objects: |
      array:
        - |
          objectName: postgres-password
          objectType: secret
          objectAlias: DB_PASSWORD
        - |
          objectName: postgres-user
          objectType: secret
          objectAlias: DB_USER