apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agenda-dev
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Reidark0/infra-completa.git
    targetRevision: main
    path: deploy/dev
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
